"""drop agent run resumed from

Revision ID: 008899fa663b
Revises: 70def0870858
Create Date: 2026-10-06 08:23:50.175155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008899fa663b'
down_revision: Union[str, Sequence[str], None] = '70def0870858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_runs_resumed_from_run_id'), table_name='agent_runs')
    op.drop_constraint(op.f('agent_runs_resumed_from_run_id_fkey'), 'agent_runs', type_='foreignkey')
    op.drop_column('agent_runs', 'resumed_from_run_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('resumed_from_run_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agent_runs_resumed_from_run_id_fkey'), 'agent_runs', 'agent_runs', ['resumed_from_run_id'], ['id'])
    op.create_index(op.f('ix_agent_runs_resumed_from_run_id'), 'agent_runs', ['resumed_from_run_id'], unique=False)
    # ### end Alembic commands ###
