"""add task summary

Revision ID: 29ad196b3c46
Revises: 5e62c0de2fd0
Create Date: 2026-10-05 09:28:14.955804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ad196b3c46'
down_revision: Union[str, Sequence[str], None] = '5e62c0de2fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_tasks', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_tasks', 'summary')
    # ### end Alembic commands ###
