"""add research job lease

Revision ID: 53cb5d0cf7e6
Revises: 62559547644f
Create Date: 2026-10-06 09:48:32.831347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cb5d0cf7e6'
down_revision: Union[str, Sequence[str], None] = '62559547644f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_jobs', sa.Column('lease_token', sa.String(length=255), nullable=True))
    op.add_column('research_jobs', sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_jobs', 'lease_expires_at')
    op.drop_column('research_jobs', 'lease_token')
    # ### end Alembic commands ###
