"""add agent token usage and cost

Revision ID: 65122ee4276a
Revises: 79a17d2008f3
Create Date: 2026-10-05 16:10:19.108411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65122ee4276a'
down_revision: Union[str, Sequence[str], None] = '79a17d2008f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('agent_runs', sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('agent_runs', sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('agent_runs', sa.Column('estimated_cost_usd', sa.Double(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'estimated_cost_usd')
    op.drop_column('agent_runs', 'total_tokens')
    op.drop_column('agent_runs', 'output_tokens')
    op.drop_column('agent_runs', 'input_tokens')
    # ### end Alembic commands ###
