"""add agent run resumed from

Revision ID: 70def0870858
Revises: b52785bbeba9
Create Date: 2026-10-06 07:42:47.774843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70def0870858'
down_revision: Union[str, Sequence[str], None] = 'b52785bbeba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('resumed_from_run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_agent_runs_resumed_from_run_id'), 'agent_runs', ['resumed_from_run_id'], unique=False)
    op.create_foreign_key(
        'agent_runs_resumed_from_run_id_fkey',
        'agent_runs', 'agent_runs', ['resumed_from_run_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'agent_runs_resumed_from_run_id_fkey',
        'agent_runs',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_agent_runs_resumed_from_run_id'), table_name='agent_runs')
    op.drop_column('agent_runs', 'resumed_from_run_id')
    # ### end Alembic commands ###
