"""add agent run checkpoint state

Revision ID: b52785bbeba9
Revises: d7733b94b886
Create Date: 2026-10-05 16:41:42.948116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b52785bbeba9'
down_revision: Union[str, Sequence[str], None] = 'd7733b94b886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_runs', sa.Column('state_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'state_updated_at')
    op.drop_column('agent_runs', 'state')
    # ### end Alembic commands ###
