"""add job event tool and duration

Revision ID: c55e3c6c8391
Revises: 15c3ed01f730
Create Date: 2026-10-06 14:34:52.938025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55e3c6c8391'
down_revision: Union[str, Sequence[str], None] = '15c3ed01f730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_events', sa.Column('tool', sa.String(length=50), nullable=True))
    op.add_column('job_events', sa.Column('duration_ms', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_events', 'duration_ms')
    op.drop_column('job_events', 'tool')
    # ### end Alembic commands ###
