"""make agent run cost nullable

Revision ID: d7733b94b886
Revises: 65122ee4276a
Create Date: 2026-10-05 16:33:54.434773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7733b94b886'
down_revision: Union[str, Sequence[str], None] = '65122ee4276a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NULL now means "pricing unknown", so drop the '0' default too;
    # otherwise new rows would claim a cost of $0.
    op.alter_column('agent_runs', 'estimated_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               server_default=None,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL would fail on rows with an unknown cost; store them as 0.
    op.execute(
        "UPDATE agent_runs SET estimated_cost_usd = 0 "
        "WHERE estimated_cost_usd IS NULL"
    )
    op.alter_column('agent_runs', 'estimated_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###
