"""add step created_at

Revision ID: d83a0d45cd74
Revises: 4fba1ab86120
Create Date: 2026-10-06 15:11:03.647609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83a0d45cd74'
down_revision: Union[str, Sequence[str], None] = '4fba1ab86120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable until existing steps are filled in.
    op.add_column('research_steps', sa.Column('created_at', sa.DateTime(), nullable=True))

    # Existing steps: when their first result was saved (close to when the
    # search ran), or failing that when their task was created.
    op.execute(
        """
        UPDATE research_steps AS step
        SET created_at = COALESCE(
            (
                SELECT MIN(result.created_at)
                FROM research_results AS result
                WHERE result.step_id = step.id
            ),
            (
                SELECT task.created_at
                FROM research_tasks AS task
                WHERE task.id = step.task_id
            )
        )
        """
    )

    op.alter_column('research_steps', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_steps', 'created_at')
    # ### end Alembic commands ###
