"""add job attempts

Revision ID: f3defeeda75b
Revises: 1287a654ca3b
Create Date: 2026-10-06 10:20:32.085755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3defeeda75b'
down_revision: Union[str, Sequence[str], None] = '1287a654ca3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_attempts_job_id'), 'job_attempts', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_attempts_worker_id'), 'job_attempts', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_attempts_worker_id'), table_name='job_attempts')
    op.drop_index(op.f('ix_job_attempts_job_id'), table_name='job_attempts')
    op.drop_table('job_attempts')
    # ### end Alembic commands ###
