"""add step duration and require tool

Revision ID: fc3867452019
Revises: 9328e21c46cb
Create Date: 2026-10-05 14:07:23.692050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3867452019'
down_revision: Union[str, Sequence[str], None] = '9328e21c46cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_steps', sa.Column('duration_ms', sa.Double(), nullable=True))
    op.alter_column('research_steps', 'tool',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_steps', 'tool',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('research_steps', 'duration_ms')
    # ### end Alembic commands ###
