"""add agent iteration

Revision ID: ff2fb1047e22
Revises: 29ad196b3c46
Create Date: 2026-10-05 11:23:34.661245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2fb1047e22'
down_revision: Union[str, Sequence[str], None] = '29ad196b3c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default lets this run on a table that already has rows.
    op.add_column('research_steps', sa.Column('iteration', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_steps', 'iteration')
    # ### end Alembic commands ###
